New version of OpenOfficeUNODecomposition.jar
I don't know what happened, but this is the latest and greatest.

However, still seeing the following error on open-dev:

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/star/uno/Exception
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at com.sun.star.lib.loader.Loader.main(Loader.java:142)
Caused by: java.lang.ClassNotFoundException: com.sun.star.uno.Exception
	at com.sun.star.lib.loader.Loader$CustomURLClassLoader.findClass(Loader.java:365)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.sun.star.lib.loader.Loader$CustomURLClassLoader.loadClass(Loader.java:376)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClassInternal(Unknown Source)
	... 5 more