Merged revisions 66158,66770,67021-67022,67106,67118,67323,67386-67397,67425-67427,67430,67439,67641,67656,67658,67681,67686,67733-67734,67743-67744,67759,67765-67766 via svnmerge from https://source.sakaiproject.org/contrib/ocw2/trunk/tool
........
  r66158 | kwc@umich.edu | 2010-02-16 11:15:02 -0500 (Tue, 16 Feb 2010) | 5 lines
  
  Remove hachoir code and uses of it
  
  The hachoir license is incompatible with our desired licensing.
  We aren't really using it anyway, so remove it and the code
  that could possibly try to use it.
........
  r66770 | lotia@umich.edu | 2010-03-23 13:01:04 -0400 (Tue, 23 Mar 2010) | 8 lines
  
  Initial commit delete_extra_records.sql
  
  This file has a set of canned queries that facilitate the deletion of
  all records that aren't relevant to the specified course IDs. Not sure
  if it works perfectly yet, but appears to mostly do the job.
  
  I've also squeezed in some whitspace cleanups and removals of hard
  tabs in oer_decompose.php
........
  r67021 | kwc@umich.edu | 2010-04-06 16:11:45 -0400 (Tue, 06 Apr 2010) | 3 lines
  
  Add Open Office code, etc.
  
  Add code to use Open Office for decomp and recomp of Powerpoint materials.
........
  r67022 | kwc@umich.edu | 2010-04-06 16:11:47 -0400 (Tue, 06 Apr 2010) | 7 lines
  
  Use the new Open Office code to do decomp for Powerpoint files
  
  Change the decomposition code to use the new OpenOffice decomp
  library for files with suffixes .ppt, .pptx, and .odp.
  The code to obtain context images is changed to obtain the
  context images extracted during the decomp phase for these
  file types.
........
  r67106 | kwc@umich.edu | 2010-04-12 10:15:21 -0400 (Mon, 12 Apr 2010) | 14 lines
  
  Fix OpenOffice invocation for apache user on Linux
  
  The apache user has no shell, and is not allowed to create
  files or directories in its home directory.  When invoking
  the OO decomp program, set HOME to /tmp so that necessary
  configuration information can be created and referenced by
  the apache user.
  
  Also note that the registration wizard must be disabled.
  Otherwise, the OpenOffice instance is never ready to accept
  connections, and the UNO code is unable to connect to the
  soffice program that is started.  See:
  http://wiki.services.openoffice.org/wiki/Documentation/Administration_Guide/Deactivating_Registration_Wizard
  for more information on how to disable this PITA!
........
  r67118 | kwc@umich.edu | 2010-04-12 16:31:19 -0400 (Mon, 12 Apr 2010) | 11 lines
  
  Add CitationManipulate class.  Add boilerplate option
  
  From Ali Asad Lotia:
  Add new CitationManipulate class to handle parsing of
  a citation string.  Remove local parsing methods from
  DecompImpress.
  
  Add command-line and json option to specify the location
  of the boilerplate slides to be added to the front of
  a PowerPoint slide when saving.  Ali supplied a good
  start at this.
........
  r67323 | kwc@umich.edu | 2010-04-26 11:39:59 -0400 (Mon, 26 Apr 2010) | 3 lines
  
  Fix an exception when no boilerplate file is specified.
  
  Also, properly handle a boilerplate specification on the command line.
........
  r67386 | lotia@umich.edu | 2010-04-27 23:06:10 -0400 (Tue, 27 Apr 2010) | 6 lines
  
  Removed "Add more information" from CO details.
  
  As part of the set of UI modifications required for the first phase of
  OERca changes, the "Add more information" section is removed from the
  Content Object editing form in both the original and the replacement
  panes.
........
  r67387 | lotia@umich.edu | 2010-04-27 23:06:16 -0400 (Tue, 27 Apr 2010) | 14 lines
  
  Cleanup data from materials selection form.
  
  The materials selection form submits material ids as POST variables.
  The controller processing these values wasn't doing any validation on
  the submitted values. We now do some xss cleaning and also check to see
  if the material id's submitted are numeric. If not, we return to the
  original page and print an error.
  
  Also did many whitespace and formatting cleanups on:
  event-rules.js
  courses.php
  materials.php
  course.php
  material.php
........
  r67388 | lotia@umich.edu | 2010-04-27 23:06:23 -0400 (Tue, 27 Apr 2010) | 6 lines
  
  Assorted untabification and whitespace cleanups.
  
  Cleaned up whitespace in the following files to make them readable.
  tool/system/application/libraries/oer_decompose.php
  tool/system/application/libraries/oer_decompose_openoffice.php
  tool/system/application/models/coobject.php
........
  r67389 | lotia@umich.edu | 2010-04-27 23:06:28 -0400 (Tue, 27 Apr 2010) | 10 lines
  
  material sql query and related changes for recomp.
  
  The sql query was tweaked to fetch object information for a specified
  set of materials.
  
  Additionally, we process the fetched data to provide the information
  needed for recomp.
  
  The returned array is structured differently which also required the
  revision of existing code.
........
  r67390 | lotia@umich.edu | 2010-04-27 23:06:33 -0400 (Tue, 27 Apr 2010) | 5 lines
  
  Fix get_material_info SQL to get no-CO materials.
  
  The SQL query in get_material_info was not selecting materials that did
  not have any content objects, this commit ensures that all materials are
  selected.
........
  r67391 | lotia@umich.edu | 2010-04-27 23:06:37 -0400 (Tue, 27 Apr 2010) | 7 lines
  
  Add recomp directives to get_material_info .
  
  The material.php model returns recomp directives in the
  ['material_manip_ops'] element in each material's array. These
  directives are used for the JSON file generated for the openoffice
  recomp tool. in the ['material_manip_ops'] value of the returned
  array.
........
  r67392 | lotia@umich.edu | 2010-04-27 23:06:42 -0400 (Tue, 27 Apr 2010) | 4 lines
  
  Fix comments, indentation in material controller.
  
  The indentation had gotten quite messed up and some potentially
  confusing typecasts were not commented. This commit fixes those issues.
........
  r67393 | lotia@umich.edu | 2010-04-27 23:06:47 -0400 (Tue, 27 Apr 2010) | 4 lines
  
  Generate a working JSON input file for recomp.
  
  The material model and materials controller now include functionality to
  create a JSON input file for the openoffice recomp tool.
........
  r67394 | lotia@umich.edu | 2010-04-27 23:06:52 -0400 (Tue, 27 Apr 2010) | 6 lines
  
  Whitespace cleanups in ocw_utils library.
  
  This function is used a lot and over time, had become largely illegible
  because of the state of the formatting of the code. I needed to use some
  functions and couldn't read them at all. So some whitespace and
  formatting cleanups the rescue.
........
  r67395 | lotia@umich.edu | 2010-04-27 23:06:57 -0400 (Tue, 27 Apr 2010) | 8 lines
  
  Add recomp to the decompose libs.
  
  Since much of the environment was defined, it seemed silly to create a
  whole separate recomp library, so the recomp functionality was added to
  the decomp libs.
  
  This commit also includes to delete the decomp directory and the files
  in it..
........
  r67396 | lotia@umich.edu | 2010-04-27 23:07:02 -0400 (Tue, 27 Apr 2010) | 4 lines
  
  Revert whitespace cleanups in ocw_utils lib.
  
  Something broke when I attempted to clean up whitespace. Lesson learned
  to leave well enough alone.
........
  r67397 | lotia@umich.edu | 2010-04-27 23:07:07 -0400 (Tue, 27 Apr 2010) | 3 lines
  
  Include recomped files in download archive.
  
  Recomped files are now included in the generated archives.
........
  r67425 | lotia@umich.edu | 2010-04-29 02:54:31 -0400 (Thu, 29 Apr 2010) | 7 lines
  
  Further fixes to recomp boilerplate code.
  
  Several whitespace and indentation cleanups in
  tool/system/application/models/material.php
  tool/system/application/controllers/materials.php
........
  r67426 | lotia@umich.edu | 2010-04-29 03:28:27 -0400 (Thu, 29 Apr 2010) | 7 lines
  
  Add boilerplate slides file and add config param.
  
  The boilderplate slides were added to tool/decomposition as a file named
  RecompBoilerplate.ppt.
  
  The layout.template file in tool/system/application/config now contains
  a line that is supposed to point to the boilerplate file.
........
  r67427 | lotia@umich.edu | 2010-04-29 03:28:34 -0400 (Thu, 29 Apr 2010) | 4 lines
  
  Commented out logging in oer_create_archive.
  
  The zip archive creation method was logging a bunch of stuff to the
  apache error log. The logging directives are now commented out.
........
  r67430 | kwc@umich.edu | 2010-04-29 10:02:49 -0400 (Thu, 29 Apr 2010) | 1 line
  
  Fix @OERTOP@ reference, and make our boilerplate file the default
........
  r67439 | lotia@umich.edu | 2010-04-30 01:11:34 -0400 (Fri, 30 Apr 2010) | 23 lines
  
  Add co image remove on recomp.
  
  CO images with a "Remove and Annotate" final action or recommended
  action in cases where there is no final action are replaced with an
  image that states that the image has been removed. This informational
  image replacement is accompanied by a citation that must be modified by
  the dScribe.
  
  The material model also contains setters to specify a different removed
  image placeholder from the system default. It also contains a setter for
  the accompanying citation.
  
  Downloaded files are now always delivered in zip form even if a single
  file is selected for download. This change was a quick way to make sure
  that the recomped version was delivered in cases where a single file was
  selected for download.
  
  Added a standard image that is put in place of removed images.
  
  Added configuration directives to
  tool/system/application/config/layout.template for configuring the path
  to the "removed image" replacement file and also to specify the
  citation text for removed images.
........
  r67641 | lotia@umich.edu | 2010-05-12 18:47:24 -0400 (Wed, 12 May 2010) | 10 lines
  
  Add citation instruction tooltip in object edit.
  
  The "Source Information" dialog box in both object and replacement edit
  screens now has a tooltip that brings up instructions on citation
  formatting.
  
  Making stuff align required some very dodgy css. This css is inline. The
  current template code is so hideous that attempting to do things the
  right way results in everything getting ugly. So for now, this is an
  example in how NOT to do css or tooltips for that matter.
........
  r67656 | kwc@umich.edu | 2010-05-14 10:45:19 -0400 (Fri, 14 May 2010) | 13 lines
  
  OpenOffice decomp/recomp fixes
  
  - Add code to assure that replacement images are inserted
    in their original aspect ratio.  (Bounded by the size of
  	the original they are replacing.
  - Add code to allow replacement of non-GraphicObjectShape
    originals.
  - Fix the image/shape number on the long citation page
    (show image number rather than index number)
  - Fix (many) cases where the boilerplate pages were not
    showing up, with blank pages instead and in the wrong
  	place.
  - Update some error logging.
........
  r67658 | kwc@umich.edu | 2010-05-14 11:30:34 -0400 (Fri, 14 May 2010) | 3 lines
  
  Install updated Boilerplate file
  
  Add the generic Boilerplate file from Piet.
........
  r67681 | kwc@umich.edu | 2010-05-18 09:14:13 -0400 (Tue, 18 May 2010) | 15 lines
  
  Another update to the replacment aspect ratio calculation
  
  Fix the replacement size calculation.
  
  If the original's proportion (width / height) is greater than
  the replacement's, always use the original's height, and always
  calculate the replacement's width appropriately.
  
  replwidth = (origheight * replprop)
  
  If the original's proportion is less than the replacement's,
  always use the original's width, and always calculate the
  replacements height appropriately.
  
  replheight = (origwidth / replprop)
........
  r67686 | kwc@umich.edu | 2010-05-18 13:33:24 -0400 (Tue, 18 May 2010) | 13 lines
  
  Make the shape/image number zero-based
  
  The old decomp code had page numbers starting at one and image
  numbers starting at zero.  Remove the code in the OpenOffice
  decomp code that offset the image number to make them one-based.
  Update the recomp code to expect zero-based image numbers.
  
  This allows the recomp code to work with materials that were
  decomposed with the older decomp code and the new OpenOffice
  decomp code.
  
  Remove the adjustment in _get_rec_place_info() that was there
  to make the recomp code work for the older material.
........
  r67733 | kwc@umich.edu | 2010-05-20 11:18:44 -0400 (Thu, 20 May 2010) | 1 line
  
  Debugging to see why recomp replacements aren't happening
........
  r67734 | kwc@umich.edu | 2010-05-20 11:18:46 -0400 (Thu, 20 May 2010) | 14 lines
  
  Fix off-by-one issue with citations, fix image removal issue
  
  After changing the off-by-one issue with the shape numbers,
  the citations had an issue.  This resolves that.
  
  After adding code to allow replacement of non-GraphicObjectShape
  shapes, an issue arose when several replacements or citations
  occur on the same page.  To replace the non-GraphicObjectShape
  we remove the original shape and add a new GraphicObjectShape.
  The removal of the original shape causes all the following
  shapes on the page to get shifted up.  This causes problems
  when one of those images needs to be cited or replaced since
  its index has changed.  To fix this, we delay the removals
  until all the other operations on the document are complete.
........
  r67743 | kwc@umich.edu | 2010-05-20 14:07:35 -0400 (Thu, 20 May 2010) | 4 lines
  
  Remove accidently committed debugging
  
  Comment out log message and extra save of the
  recomp json file.
........
  r67744 | kwc@umich.edu | 2010-05-20 14:21:00 -0400 (Thu, 20 May 2010) | 19 lines
  
  New version of OpenOfficeUNODecomposition.jar
  
  I don't know what happened, but this is the latest and greatest.
  
  However, still seeing the following error on open-dev:
  
  Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/star/uno/Exception
  	at java.lang.Class.getDeclaredMethods0(Native Method)
  	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
  	at java.lang.Class.getMethod0(Unknown Source)
  	at java.lang.Class.getMethod(Unknown Source)
  	at com.sun.star.lib.loader.Loader.main(Loader.java:142)
  Caused by: java.lang.ClassNotFoundException: com.sun.star.uno.Exception
  	at com.sun.star.lib.loader.Loader$CustomURLClassLoader.findClass(Loader.java:365)
  	at java.lang.ClassLoader.loadClass(Unknown Source)
  	at com.sun.star.lib.loader.Loader$CustomURLClassLoader.loadClass(Loader.java:376)
  	at java.lang.ClassLoader.loadClass(Unknown Source)
  	at java.lang.ClassLoader.loadClassInternal(Unknown Source)
  	... 5 more
........
  r67759 | kwc@umich.edu | 2010-05-21 10:33:03 -0400 (Fri, 21 May 2010) | 6 lines
  
  Only the first original and COs were being processed
  
  I believe the indentation caused this.  The recomp files, etc.,
  were being added after the first material was processed and the
  zip file shipped off.  Move the recomp and shipment stuff outside
  the for() loop.
........
  r67765 | lotia@umich.edu | 2010-05-21 15:17:45 -0400 (Fri, 21 May 2010) | 4 lines
  
  Change citation help from tooltip to slider.
  
  The citation help no longer appears in a tooltip. It is now preseented
  in a slider.
........
  r67766 | kwc@umich.edu | 2010-05-21 16:10:58 -0400 (Fri, 21 May 2010) | 4 lines
  
  Remove some no longer used code from _download_material()
  
  The $num_files variable is no longer used. Remove it and
  the code that calculated it.


........
Merged revisions 67848 via svnmerge from 
https://source.sakaiproject.org/contrib/ocw2/trunk/tool

........
  r67848 | kwc@umich.edu | 2010-05-25 16:49:38 -0400 (Tue, 25 May 2010) | 3 lines
  
  Replace old "removed_image.png" with a higher resolution image
  
  Kept Pieter's whole new name since the suffix had to change anyway.


........
Merged revisions 67873 via svnmerge from 
https://source.sakaiproject.org/contrib/ocw2/trunk/tool

........
  r67873 | kwc@umich.edu | 2010-05-27 12:01:48 -0400 (Thu, 27 May 2010) | 6 lines
  
  The replacement stuff should use "do_replacement_update" class
  
  The replacement citation field has class "do_object_update", while
  it should be using class "do_replacement_update".  I don't know why
  it was causing the same citation information to be saved for *both*
  the replacement and original, but this seems to fix it anyway!



........
Merged revisions 67882 via svnmerge from 
https://source.sakaiproject.org/contrib/ocw2/trunk/tool

........
  r67882 | kwc@umich.edu | 2010-05-27 15:05:24 -0400 (Thu, 27 May 2010) | 3 lines
  
  Really (I hope!) fix the replacement citation information
  
  I'm [pretty] sure it is correct now!
........
Merged revisions 68129,69176 via svnmerge from 
https://source.sakaiproject.org/contrib/ocw2/trunk/tool

........
  r68129 | lotia@umich.edu | 2010-06-09 23:00:09 -0400 (Wed, 09 Jun 2010) | 15 lines
  
  Config changes to allow running outside webroot.
  
  The layout.template file contained several lines that had
  $_SERVER['DOCUMENT_ROOT'].'/@OERTOP@'
  where @OERTOP@ was replaced with whatever subdirectory of the webroot
  in which OERca was installed. However, when OERca was installed outside
  the webroot several things break and CO images etc. no longer show up.
  
  This change requires that the user specify the absolute path to the
  OERca install directory near the top of the layout.php file and things
  should work instead of having to replace all occurrences of @OERTOP@.
  
  Note, it should be the directory where the OERca webapp is installed.
  Not the top level of the SVN/Git repository. The name for this folder in
  the SVN repository is "tool".
........
  r69176 | kwc@umich.edu | 2010-07-13 14:42:58 -0400 (Tue, 13 Jul 2010) | 9 lines
  
  Skip boilerplate processing
  
  Change the java code to skip the attempt to add boilerplate pages
  which is causing issues on the Linux machines!
  
  Fix a compile error that somehow surfaced by adding a missing cast.
  
  Add a log message to indicate how many materials in a download batch
  should get recomped.
........